# Generated by Django 3.2.12 on 2022-04-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brockU', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='restrictions',
            field=models.TextField(blank=True),
        ),
    ]
