# Generated by Django 3.2.13 on 2022-04-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brockU', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
