# Generated by Django 3.2.13 on 2022-04-28 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('brockU', '0002_subject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('time', models.CharField(blank=True, max_length=5)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brockU.course')),
            ],
        ),
    ]
