version: '3.9'
services:
  brockDB:
    image: postgres
    volumes:
      - ./data/BrockDB:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=badgers
      - POSTGRES_USER=badgers
      - POSTGRES_PASSWORD=badgers
  niagaraDB:
    image: postgres
    volumes:
      - ./data/NiagraDB:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=niagara
      - POSTGRES_USER=niagara
      - POSTGRES_PASSWORD=niagara
  backend:
    build: backend
    command: gunicorn config.wsgi --bind 0.0.0.0:2022
    volumes:
      - ./backend:/code
    ports:
      - "2022:2022"
    environment:
      - BROCKDB_NAME=badgers
      - BROCKDB_USER=badgers
      - BROCKDB_PASSWORD=badgers
      - NIAGARADB_NAME=niagara
      - NIAGARADB_USER=niagara
      - NIAGARADB_PASSWORD=niagara
    depends_on:
      - brockDB
      - niagaraDB
  web:
    build: web
    ports:
      - 80:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend